version: '3'

services:
  expo:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
