version: "3.9"

services:
  expo:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    develop:
      watch:
        - path: ./
          target: /app
          action: sync
    working_dir: /app
    tty: true
